/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testReadFiles(){
//linter/src/test/java/resources/noErrors.js
        String file0 ="./src/test/java/resources/noErrors.js";
        String answer0= "";
        assertEquals(answer0, App.readFiles(file0));

        String fileOneErr ="./src/test/java/resources/oneErrors.js";
        String answerOneErr= "error \"Line 7: Missing semicolon.\"\n";
        assertEquals(answerOneErr, App.readFiles(fileOneErr));

        String file ="./src/test/java/resources/fewErrors.js";
        String answer= "error \"Line 3: Missing semicolon.\"\nerror \"Line 5: Missing semicolon.\"\n";
        assertEquals(answer, App.readFiles(file));

        String fileMany="./src/test/java/resources/manyErrors.js";
        String answerMany= "error \"Line 1: Missing semicolon.\"\nerror \"Line 3: Missing semicolon.\"\nerror \"Line 5: Missing semicolon.\"\nerror \"Line 7: Missing semicolon.\"\n";
        assertEquals(answerMany, App.readFiles(fileMany));

        String file2 ="./src/test/java/resources/empty.js";
        String answer2= "";
        assertEquals(answer2, App.readFiles(file2));



    }
}
