/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import javax.sound.sampled.Line;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

//        String path= "resources/gates.js";
//        System.out.println(readFiles(path));
        
    }


    public static String readFiles(String pathPassed){
        StringBuilder holdErrors =new StringBuilder();
        Path path=Paths.get(pathPassed);
        ArrayList<String> finalLines = new ArrayList<String>();
        try{
            List<String> fileLines = Files.readAllLines(path);

            int lineNumber=0;

           for (String line: fileLines){
               lineNumber=lineNumber+1;
                if(!line.contains(";")
                        &&!line.contains("{")
                        &&!line.contains("}")
                        &&!line.contains("if")
                        &&!line.contains("//")
                        &&!line.contains("else")
                        &&!line.isEmpty()){

                    holdErrors.append("error "+"\"Line "+lineNumber+": Missing semicolon.\"").append("\n");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return holdErrors.toString();
    }

}
