/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {

    }
    @Test public void constructorRestaurant(){ // Testing the Restaurant's constructor.
        String name="Ali";
        int stars= 42;
        int price =20;

        Restaurant R = new Restaurant(name,stars,price);
        assertEquals(5, R.getStars());
        assertEquals("$$",R.getPrice());
        assertEquals("Ali" , R.getName());
    }

    @Test public void constructorOfReview(){ // Testing Review's constructor.
        int stars=10;
        String body = "It's very amazing restaurant";
        String author = "Mohammad";
        Review review =new Review(stars, body, author);

        assertEquals(5 ,review.getStars());
        assertEquals("It's very amazing restaurant" , review.getBody());
        assertEquals("Mohammad", review.getAuthor());
    }

    @Test public void addReviewTest(){
        Review review = new Review(10,"Beautiful" , "Ali");
        assertEquals("Review{stars=5, body='Beautiful', author='Ali'}",review.toString() );
    }

    @Test public void add_Remove_MovieTest(){
        Theater theater =new Theater();
        theater.addMovie("First World war");
        theater.addMovie("Second World war");
        ArrayList<String> listOfMovies = new ArrayList<String>();
        listOfMovies.add("First World war");
        listOfMovies.add("Second World war");
        listOfMovies.add("Red world");
        assertEquals(listOfMovies , theater.addMovie("Red world"));

        listOfMovies.remove(1);
        assertEquals(listOfMovies ,theater.removeMovie(1));
    }

    @Test public void TheaterMovie(){
        Theater theater =new Theater();
        assertEquals( "Review[stars: 1, body: good theater, author: NoorEdden]", theater.TheaterOnly(1,"good theater" , "NoorEdden"));
        assertEquals( "Review[stars: 6, body: Very amazing, author: Kimon, movie: The Life]", theater.TheaterWithMovie(6,"Very amazing" , "Kimon" ,"The Life"));
    }

}
