/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {

    }
    @Test public void constructorRestaurant(){ // Testing the Restaurant's constructor.
        String name="Ali";
        int stars= 42;
        int price =20;

        Restaurant R = new Restaurant(name,stars,price);
        assertEquals(5, R.getStars());
        assertEquals("$$",R.getPrice());
        assertEquals("Ali" , R.getName());
    }

    @Test public void constructorOfReview(){ // Testing Review's constructor.
        int stars=10;
        String body = "It's very amazing restaurant";
        String author = "Mohammad";
        Review review =new Review(stars, body, author);

        assertEquals(5 ,review.getStars());
        assertEquals("It's very amazing restaurant" , review.getBody());
        assertEquals("Mohammad", review.getAuthor());
    }

    @Test public void addReviewTest(){
        Review review = new Review(10,"Beautiful" , "Ali");
        assertEquals("Review{stars=5, body='Beautiful', author='Ali'}",review.toString() );
    }
}
